baseURL: "https://emilien-foissotte.github.io/"
languageCode: "en-us"
title: "Blog | Émilien F. "
theme: "PaperMod"
paginate: 5

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: About Me
      url: /me/
      weight: 4
    - name: Search
      url: /search/
      weight: 4
    - name: Projects
      url: https://www.datascienceportfol.io/EmilienFoissotte
      weight: 5
    - name: Posts
      url: /archives/
      weight: 6
    - name: Tags
      url: /tags/
      weight: 7

taxonomies:
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Portfolio for my work and also blog for my thoughts"
  author: Émilien Foissotte
  comments: true
  defaultTheme: auto # dark, light

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShowFullTextinRSS: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/favicon.ico"

  editPost:
    URL: "https://github.com/Emilien-Foissotte/emilien-foissotte.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  params:
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  homeInfoParams:
    Title: Hello there!
    Content: |

      -
      My name is Émilien Foissotte, welcome to my blog / portfolio 👨‍💻

      I'm a Machine Learning Engineer working on various components of MLOps stack 🤖

      -
      This website is quite fresh and still a work in progress, happy to see you here, hope you'll enjoy the look around.

      -
      Feel free to read some of my ML related ramblings about my worklife, but also other tech-adjacent items I've come accross working on side projects.

  socialIcons:
    - name: Github
      url: "https://github.com/Emilien-Foissotte"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/emilien-foissotte44/"
    - name: RSS
      url: "https://emilien-foissotte.github.io/index.xml"

  giscus:
    repo: emilien-foissotte/emilien-foissotte.github.io
    repoID: R_kgDOJLROeA
    category: Articles
    categoryID: DIC_kwDOJLROeM4CVfjs
    mapping: og:title
    inputPosition: top
    theme: light
    lang: en
