baseURL = 'https://emilien-foissotte.github.io/'
languageCode = 'en-us'
title = 'Emilien Foissotte'
theme = 'yinyang'

[author]
  email = "emilienfoissotte44@gmail.com"
  name = "Emilien Foisotte"

[params]
  headTitle = "Emilien Foissotte"
  mainSections = ["blog"]
  favicon = "/img/favicon.ico"
  [[params.socials]]
  name = "About Me"
  link = "https://emilien-foissotte.github.io/me"
  [[params.socials]]
  name = "Github"
  link = "https://github.com/Emilien-Foissotte"
  [[params.socials]]
  name = "Website"
  link = "http://emilienfoissotte.fr/website"
