baseURL: 'https://emilien-foissotte.github.io/'
languageCode:  'en-us'
title: 'Blog | Émilien F. '
theme: 'PaperMod'
paginate: 5

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: About Me
      url: /me/
      weight: 4
    - name: Search
      url: /search/
      weight: 4
    - name: Projects
      url: https://www.datascienceportfol.io/EmilienFoissotte
      weight: 5
    - name: Posts
      url: /Archives/
      weight: 6
    - name: Tags
      url: /tags/
      weight: 7

taxonomies:
  category: categories
  tag: tags

params:
  env: production
  description: "Portfolio for my work and also blog for my thoughts"
  author: Émilien Foissotte
  comments: true
  defaultTheme: auto # dark, light

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/favicon.ico"

  editPost:
    URL: "https://github.com/Emilien-Foissotte/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  outputs:
    home:
      - HTML
      - RSS
      - JSON

  homeInfoParams:
    Title: Hello there!
    Content: |

      -
      My name is Émilien Foissotte, welcome to my blog / portfolio 👨‍💻

      I'm a Machine Learning Engineer working on various components of MLOps stack 🤖

      -
      This swebsite is quite fresh and still a work in progress, happy to see you here, hope you'll enjoy the look around.

      -
      Feel free to read some of my ML related ramblings about my worklife, but also other tech-adjacent items I've come accross working on side projects.

  socialIcons:
        - name: github
          url: "https://github.com/Emilien-Foissotte"
        - name: LinkedIn
          url: "https://www.linkedin.com/in/emilien-foissotte44/"

  giscus:
    repo: emilien-foissotte/emilien-foissotte.github.io
    repoID: R_kgDOJLROeA
    category: Articles
    categoryID: DIC_kwDOJLROeM4CVfjs
    mapping: og:title
    inputPosition: top
    theme: light
    lang: en
