baseURL: "https://emilien-foissotte.github.io/"
title: "Blog | Émilien F. "
theme: "PaperMod"
# paginate: 5
pagination:
  pagerSize: 5
enableRobotsTXT: true

languages:
  en:
    languageName: ":uk:"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
    menu:
      main:
        - name: About Me
          url: /me/
          weight: 3
        - name: Search
          url: /search/
          weight: 4
        - name: Projects
          url: https://www.datascienceportfol.io/EmilienFoissotte
          weight: 5
        - name: Posts
          url: /archives/
          weight: 6
        - name: Tags
          url: /tags/
          weight: 7

  fr:
    languageName: ":fr:"
    weight: 2
    taxonomies:
      category: FRcategories
      tag: FRtags
    menu:
      main:
        - name: À Propos
          url: /fr/me/
          weight: 3
        - name: Recherche
          url: /fr/search/
          weight: 4
        - name: Projets
          url: https://www.datascienceportfol.io/EmilienFoissotte
          weight: 5
        - name: Posts
          url: /archives/
          weight: 6
        - name: Catégories
          url: /frtags/
          weight: 7

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Portfolio for my work and also blog for my thoughts"
  author: Émilien Foissotte
  comments: true
  defaultTheme: auto # dark, light
  social: true


  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShowFullTextinRSS: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/favicon.ico"
    favicon16x16: "/img/favicon-16x16.png"
    favicon32x32: "/img/favicon-32x32.png"
    apple_touch_icon: "/img/apple-touch-icon.png"

  editPost:
    URL: "https://github.com/Emilien-Foissotte/emilien-foissotte.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  params:
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  homeInfoParams:
    Title: Hello there!
    Content: |

      -
      My name is Émilien Foissotte, welcome to my blog / portfolio 👨‍💻

      I'm a Machine Learning Engineer working on various components of MLOps stack 🤖

      -
      This website is quite fresh and still a work in progress, happy to see you here, hope you'll enjoy the look around.

      -
      Feel free to read some of my ML related ramblings about my worklife, but also other tech-adjacent items I've come accross working on side projects.

      -
      <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.

  socialIcons:
    - name: Github
      url: "https://github.com/Emilien-Foissotte"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/emilien-foissotte44/"
    - name: RSS
      url: "https://emilien-foissotte.github.io/index.xml"
    - name: LICENSE
      url: "https://creativecommons.org/licenses/by-sa/4.0/"

  giscus:
    repo: emilien-foissotte/emilien-foissotte.github.io
    repoID: R_kgDOJLROeA
    category: Articles
    categoryID: DIC_kwDOJLROeM4CVfjs
    mapping: og:title
    inputPosition: top
    theme: light
    lang: en

ignoreLogs:
  - 'warning-goldmark-raw-html'

